export const LINKANDROID_TASK_API_PROMPT = [
    '===== 运行环境 =====',
    '- 必须 import la（不是 import linkandroid！），默认第一步写 device = la.device()',
    '- 只能用 la 库 API，禁止使用 phone_screen、adb、subprocess、os.system、Selenium、Appium、Playwright',
    '- 输出用 Python 内置 print()，不要用 la.print()（la 没有 print API）',
    '- 默认单设备，不要默认同步操作多台手机',
    '',
    '===== 基础结构 =====',
    'import la',
    'device = la.device()         # 单设备代理（推荐）',
    '# device.raw() 获取原生 uiautomator2 Device',
    '',
    '===== 按键 =====',
    'device.home()',
    'device.back()',
    'device.menu() / device.recent() / device.power()',
    'device.press("home") / press("back") / press("enter") / press("delete") / press("search") / press("volume_up")',
    '',
    '===== 坐标点击/滑动 =====',
    'device.click(x, y)',
    'device.tap(x, y)             # click 别名',
    'device.doubleClick(x, y)',
    'device.longClick(x, y)',
    'device.swipe(fx, fy, tx, ty)',
    'device.swipeExt("up")       # down/left/right',
    'device.swipeTo("up", text="设置")  # 滑动直到目标出现',
    'device.drag(fx, fy, tx, ty)',
    '',
    '===== 元素选择 =====',
    'device.selector(text="设置")                        # Selector 对象',
    'device.select(id="com.android.settings:id/search")  # selector 别名',
    'device.find(text="确定")                            # UIElement | None',
    'device.findAll(text="确定", className="android.widget.Button")',
    'device.exists(text="确定")                          # bool',
    'device.count(text="确定")                           # int',
    'device.wait(text="确定", timeout=10)                # bool 等待元素出现',
    '',
    '===== 快捷点击 =====',
    'device.tapText("确定")              # 按 text 点击',
    'device.tapText("确定", timeout=5)   # 等待最多5秒后点击',
    'device.tapDesc("更多", timeout=5)   # 按 content-desc 点击',
    'device.tapId("com.pkg:id/submit")   # 按 resource-id 点击',
    'device.tapExists(text="允许", timeout=3)            # 存在则点击, 返回 bool',
    'device.clickIfExists(...)                         # tapExists 别名',
    '',
    '===== 元素交互 =====',
    'device.clickElement(element)         # 点击元素对象',
    'device.clickCenter(element)          # 点击元素中心',
    'device.getText(element)              # str 元素文本',
    'device.getBounds(element)            # dict {left, top, right, bottom}',
    'device.center(element)                # (x, y) 中心坐标',
    'device.info(element)                  # dict 元素全部属性',
    '',
    '===== 文字输入 =====',
    'device.inputText("内容", clear=True)   # 先清除再输入',
    'device.text("内容")                     # 直接输入',
    'device.clearText()                     # 清除输入框',
    'device.sendKeys("内容")                # 逐字符发送',
    '',
    '===== 截图和 XML =====',
    'device.screenshot("shot.png")          # 截图保存到文件',
    'device.dumpHierarchy()                # str 当前界面 XML',
    'device.dumpXmlToFile("ui.xml")      # 保存 XML 到文件',
    '',
    '===== 应用管理 =====',
    'device.appStart("com.android.settings")',
    'device.appStop("com.android.settings")',
    'device.appClear("com.android.settings")',
    'device.appCurrent()                    # {"package":"...", "activity":"..."}',
    'device.appList()                       # [str] 已安装应用包名列表',
    'device.currentPackage()                # str 前台应用包名',
    'device.currentActivity()               # str 前台 Activity',
    'device.appInstall(url_or_path)',
    'device.appUninstall("com.pkg")',
    '',
    '===== 设备信息 =====',
    'device.width()      # int',
    'device.height()     # int',
    'device.size()       # (w, h)',
    'device.serial()     # str 序列号',
    'device.wlanIp()    # str WiFi IP',
    'device.battery()    # dict {level, temperature, status}',
    '',
    '===== 等待和休眠 =====',
    'device.wait(timeout=5)                            # 等待设备空闲',
    'device.wait(text="设置", timeout=10)              # 等待元素出现',
    'device.waitUntil(lambda: device.exists(text="x"), timeout=10)',
    'device.waitUntilGone(text="加载中", timeout=10) # 等待元素消失',
    'device.waitActivity(".Settings", timeout=10)     # bool',
    'la.sleep(1)                    # 线程休眠 1 秒',
    'la.util.sleep(1)',
    '',
    '===== 屏幕操作 =====',
    'device.isScreenOn()    # bool',
    'device.screenOn()       # 点亮屏幕',
    'device.screenOff()      # 关闭屏幕',
    'device.unlock()          # 解锁',
    '',
    '===== 工具和网络 =====',
    'la.util.now()                                         # ISO 时间',
    'la.util.jsonLoads(\'{"a":1}\') / la.util.jsonDumps({"a":1})',
    'la.util.retry(lambda: device.exists(text="确定"), times=3, interval=1)',
    'la.http.get("https://example.com", params={"k":"v"})',
    'la.http.post("https://example.com", json={"k":"v"})',
    'la.http.request("GET", url, **kwargs)',
    'la.http.json("POST", url, json={"k":"v"})            # 返回 dict',
    '',
    '===== 多设备 =====',
    'devices = la.devices()',
    'la.multi.click(devices, x, y)',
    'la.multi.back(devices)',
    'for ds in devices:',
    '    print(ds.serial())',
    '    ds.click(x, y)',
    '',
    '===== 原生 uiautomator2 出口 =====',
    'd = device.raw()  # 或 d = la.raw()',
    'd(text="设置").click()',
    'd(resourceId="pkg:id/name").exists',
    'd.xpath("//android.widget.TextView").all()',
    '',
    '===== 🔥 完整示例 1：遍历应用列表，按名称查找并打开 =====',
    'import la',
    'device = la.device()',
    'apps = device.appList()',
    'found = False',
    'for pkg in apps:',
    '    if "相册" in pkg or "gallery" in pkg or "照片" in pkg:',
    '        device.appStart(pkg)',
    '        print("opened: " + pkg)',
    '        found = True',
    '        break',
    'if not found:',
    '    print("no gallery app found")',
    '',
    '===== 🔥 完整示例 2：在当前界面查找文字并点击 =====',
    'import la',
    'device = la.device()',
    'xml = device.dumpHierarchy()',
    'if device.exists(text="确定"):',
    '    device.tapText("确定")',
    '    print("clicked 确定")',
    'elif device.exists(text="取消"):',
    '    device.tapText("取消")',
    'else:',
    '    print("no dialog found")',
    '',
    '===== 🔥 完整示例 3：滑动列表直到找到目标 =====',
    'import la',
    'device = la.device()',
    'found = device.swipeTo("up", text="蓝牙")',
    'if found:',
    '    device.tapText("蓝牙")',
    '    print("bluetooth clicked")',
    'else:',
    '    device.back()',
    '    print("not found, went back")',
    '',
    '===== 🔥 完整示例 4：等待元素出现后读取文本 =====',
    'import la',
    'device = la.device()',
    'if device.wait(text="进度", timeout=5):',
    '    elem = device.find(text="进度")',
    '    val = device.getText(elem)',
    '    print("progress=" + val)',
    '',
    '===== 🔥 完整示例 5：列出当前界面所有可点击的文字/图标按钮，然后点击指定项 =====',
    'import la',
    'import re',
    'device = la.device()',
    'device.home()',
    'xml = device.dumpHierarchy()',
    '# 提取所有可点击且有 text 的节点',
    'buttons = re.findall(r\'text="([^"]+)"[^>]*clickable="true"\', xml)',
    'if not buttons:',
    '    # 降级：提取所有有 text 的节点',
    '    buttons = re.findall(r\'text="([^"]+)"\', xml)',
    '# 去重并过滤空文本',
    'buttons = sorted(set(b for b in buttons if b.strip()))',
    'print("all_buttons=" + ", ".join(buttons))',
    'if "相册" in buttons:',
    '    device.tapText("相册")',
    '    print("clicked 相册")',
    'else:',
    '    print("相册 not found")',
    '',
    '===== 🔥 完整示例 6：打开指定应用后读取界面内容 =====',
    'import la',
    'import re',
    'device = la.device()',
    '# 查找应用商店包名',
    'apps = device.appList()',
    'store_pkg = None',
    'for pkg in apps:',
    '    if "market" in pkg or "store" in pkg or "应用商店" in pkg:',
    '        store_pkg = pkg',
    '        break',
    'if store_pkg:',
    '    device.appStart(store_pkg)',
    '    la.sleep(3)',
    '    xml = device.dumpHierarchy()',
    '    texts = re.findall(r\'text="([^"]+)"\', xml)',
    '    texts = sorted(set(t for t in texts if t.strip()))',
    '    print("recommended_apps=" + ", ".join(texts))',
    'else:',
    '    print("app_store not found")',
    '',
    '===== 硬性规则 =====',
    '1. 用户明确要求的 API 调用、固定打印文本、验证步骤必须逐字实现',
    '2. XML 和截图只能作为定位参考，不能替换或改变用户任务',
    '3. 必须基于当前任务代码修改（不是重写），保留原有结构和功能的基础上调整',
    '4. 禁止自创 API：不能使用 la.print()、device.print()、phone_screen.click、device.find_element、driver 等不存在的 API',
    '5. Python 标准输出只能用内置 print()，不存在 la.print()、device.print() 等 API',
    '6. 异常处理用 except Exception as e',
    '7. 必须返回完整可运行任务，不要引用未定义的 helper',
    '8. ⚠️ 代码必须始终以 `import la` 开头，紧接着写 `device = la.device()`。禁止省略。',
    '9. ⚠️ 当用户要求"列出""显示""获取当前页面所有/有哪些"图标、按钮、文字时，必须用 `device.dumpHierarchy()` 动态解析 XML 提取 text/content-desc，禁止硬编码列表。',
].join('\n')
